
pipeline {
    agent any
    stages {
        stage('Build'){
            steps {
                echo 'Welcome to Devops'
            }
        }        
        stage('Test'){
            steps {
                echo 'Hello World abcd'
            }
        }  
        stage('Deploy'){
            steps {
                echo 'Hi everyone how is it'
            }
         }
    }
}
