pipeline {
    agent {
        docker { image 'node:16-alpine' }
    }
        stages {
            stage('Build'){
                steps {
                    echo 'Hello World'
            stage ('Test'){
            steps {
                sh 'node --version'
            }
            
        }
           
    }
}
